### ISSUE TITLE
Break up `Env` configuration object

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-friction-surface#11]
The ideal usage pattern in this repository is to use `decline` to create many purpose built command line programs. 

This issue is an example use-case where one needs to create a main which renders pyramid instead of saving it to GeoTrellis Avro layer. Ideally the components that compute tobler, read OSM, reproject and pyramid can call be re-used and final output is rendered.

Current body is:
```scala
      (Work.roadOverlay(env) >>= { FullPyramid(env, _) }) match {
        case Failure(e) => ss.stop; throw e
        case Success(_) => ss.stop
      }
```

Potential body is something like :
```scala
      (Work.roadOverlay(env) >>= FullPyramid(env, _) >>= Render(???, _) match {
        case Failure(e) => ss.stop; throw e
        case Success(_) => ss.stop
      }
```

The remaining problem with above is that the same `Env` object is passed to all steps and and implies a single possible combination of the steps.

```scala
case class Env(
  layerName: String,
  resultName: String,
  layoutScheme: ZoomedLayoutScheme,
  numPartitions: Int,
  orcPath: String,
  tiny: Boolean,
  sparkConf: SparkConf,
  reader: LayerReader[LayerId],
  writer: LayerWriter[LayerId],
  render: Boolean
)
```

For instance if we're rendering:
- `writer` is no use
- `render` needs both a color ramp and output URI template

This issue is to break up the universal `Env` object and create `RenderTobler` main. 
Either each step can have its own object or they can be passed parameters directly from `decline` parse.

**Comment by fosskers** [comment]
If only we could compose smaller Envs, eh?

The "real" way is probably overkill here, but using [eff](https://github.com/atnos-org/eff) can let us expose smaller environments to parts of the whole. The "parent" (re: caller) operation then has multiple `Reader` effects in its signature, which together represent the whole "composed" runtime environment.

**Comment by fosskers** [comment]
Heh, sitting in a Purescript talk it now seems like the real solution is Row Polymorphism (re: anonymously composing records), but I don't think that exists in Scala.
